# Connect to a local regional LLM
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=sea-lion:v3
quarkus.langchain4j.ollama.log-requests=true
quarkus.langchain4j.ollama.log-responses=true

# Hybrid Cloud Observability
quarkus.otel.exporter.otlp.endpoint=http://otel-collector:4317